export const initialInputs = [
  { stage: "1", values: [], status: [] },
  { stage: "2", values: [], status: [] },
  { stage: "3", values: [], status: [] },
  { stage: "4", values: [], status: [] },
  { stage: "5", values: [], status: [] },
  { stage: "6", values: [], status: [] },
];

export const initalLetters = [
  { value: "Q", status: "", row: "top" },
  { value: "W", status: "", row: "top" },
  { value: "E", status: "", row: "top" },
  { value: "R", status: "", row: "top" },
  { value: "T", status: "", row: "top" },
  { value: "Y", status: "", row: "top" },
  { value: "U", status: "", row: "top" },
  { value: "I", status: "", row: "top" },
  { value: "O", status: "", row: "top" },
  { value: "P", status: "", row: "top" },
  { value: "A", status: "", row: "middle" },
  { value: "S", status: "", row: "middle" },
  { value: "D", status: "", row: "middle" },
  { value: "F", status: "", row: "middle" },
  { value: "G", status: "", row: "middle" },
  { value: "H", status: "", row: "middle" },
  { value: "J", status: "", row: "middle" },
  { value: "K", status: "", row: "middle" },
  { value: "L", status: "", row: "middle" },
  { value: "Z", status: "", row: "bottom" },
  { value: "X", status: "", row: "bottom" },
  { value: "C", status: "", row: "bottom" },
  { value: "V", status: "", row: "bottom" },
  { value: "B", status: "", row: "bottom" },
  { value: "N", status: "", row: "bottom" },
  { value: "M", status: "", row: "bottom" },
];
